export const HandleClickContinue = 'handleClickContinue'
export const HandleClickDebugButton = 'handleClickDebugButton'
export const HandleClickCallStackItem = 'handleClickCallStackItem'
export const HandleClickPause = 'handleClickPause'
export const HandleClickScopeValue = 'handleClickScopeValue'
export const HandleClickSectionBreakPoints = 'handleClickSectionBreakPoints'
export const HandleClickSectionCallstack = 'handleClickSectionCallstack'
export const HandleClickSectionScope = 'handleClickSectionScope'
export const HandleClickSectionWatch = 'handleClickSectionWatch'
export const HandleClickStepInto = 'handleClickStepInto'
export const HandleClickStepOut = 'handleClickStepOut'
export const HandleClickStepOver = 'handleClickStepOver'
export const HandleDebugInput = 'handleDebugInput'
export const HandleClickSectionHeading = 'handleClickSectionHeading'
export const HandleClickCheckBox = 'handleClickCheckBox'

// TODo use same click event listener for all debug sections
