export const PauseOnExceptions = 'PauseOnExceptions'
export const PauseOnUncaughtExceptions = 'PauseOnUncaughtExceptions'

export const DebugResume = 'DebugResume'
export const DebugPause = 'DebugPause'
export const DebugStepOver = 'DebugStepOver'
export const DebugStepInto = 'DebugStepInto'
export const DebugStepOut = 'DebugStepOut'
export const DebugRestart = 'DebugRestart'
export const DebugStop = 'DebugStop'
export const NewWatchExpression = 'new-watch-expression'
export const AddWatchExpression = 'add-watch-expression'
