export const Filter = 'filter'
export const ExplorerInput = 'ExploreerInput'
export const KeyBindingsFilter = 'keybindings-filter'
export const PauseOnExceptions = 'pause-on-exceptions'
export const PauseOnUncaughtExceptions = 'pause-on-uncaught-exceptions'

export const DebugResume = 'DebugResume'
export const DebugPause = 'DebugPause'
export const DebugStepOver = 'DebugStepOver'
export const DebugStepInto = 'DebugStepInto'
export const DebugStepOut = 'DebugStepOut'
export const DebugRestart = 'DebugRestart'
export const DebugStop = 'DebugStop'
