export const DebugContinue = 'DebugContinue'
export const DebugPause = 'DebugPause'
export const DebugStepOver = 'DebugStepOver'
export const DebugStepOut = 'DebugStepOut'
export const DebugStepInto = 'DebugStepInto'
export const DebugRestart = 'DebugRestart'
export const DebugStop = 'DebugStop'
